### ISSUE TITLE
 location of demo source code

### ISSUE THREAD

**Issue by welrikyson** [syncfusion/wpf-demos#4]
I liked the demo search engine, how could I use it?
![image](https://user-images.githubusercontent.com/28605479/56835705-fcce0080-6842-11e9-9c00-e2614798f1e3.png)

**Comment by syncsiva** [comment]
@welrikyson  Source code for WPF sample browser is not shipped during installation. Please contact [support](https://www.syncfusion.com/support/directtrac/incidents) to get a demo sample for your requirement.
