### ISSUE TITLE
Generate PDF problem

### ISSUE THREAD

**Issue by bobotan** [syncfusion/wpf-demos#5]
can i  Create 2 rows and 2 columns with A4 paper size？
every cell use Graphics fill,like Rectangle and so on..

**Comment by bobotan** [comment]
![搜狗截图20201108174618](https://user-images.githubusercontent.com/12933249/98461821-5827cf80-21ea-11eb-8881-3a6f7dff746c.jpg)

**Comment by SowmiyaLoganathan** [comment]
Hi Boboton, 
 
Thank you for contacting Syncfusion support.  
 
We can able to add graphics objects like shapes, image, etc., in PdfGridCell using [BeginCellLayout ](https://help.syncfusion.com/cr/file-formats/Syncfusion.Pdf.Grid.PdfGrid.html#Syncfusion_Pdf_Grid_PdfGrid_BeginCellLayout)event handler. We have created the sample to achieve your requirement “Create 2 rows and 2 columns with A4 size and add shapes to table cell in PDF document”. {lease find the sample for the same from below, 
 
Sample: https://www.syncfusion.com/downloads/support/directtrac/301507/ze/AddShapestoTableCell-357694296  
Output document: https://www.syncfusion.com/downloads/support/directtrac/301507/pd/Output875006889  
 
Please refer the below documentation to learn more about PdfGrid, 
Insert image to PDF table cell: https://www.syncfusion.com/kb/9746/how-to-add-two-images-in-one-pdf-table-cell-using-c-and-vb-net   
Working with shapes in PDF: https://help.syncfusion.com/file-formats/pdf/working-with-shapes  
Working with tables: https://help.syncfusion.com/file-formats/pdf/working-with-tables  
 
Please try the above sample in your end and let us know the result.  
 
Regards, 
Sowmiya Loganathan

**Comment by SyncfusionInstall** [comment]
Hi Team, 
 
We can able to add graphics objects like shapes, image, etc., in PdfGridCell using BeginCellLayout event handler. We have created the sample to illustrate this and please find the download link from below, 
 
Sample: https://www.syncfusion.com/downloads/support/directtrac/301507/ze/AddShapestoTableCell-357694296 
Output document: https://www.syncfusion.com/downloads/support/directtrac/301507/pd/Output875006889 
 
Please refer the below documentation to learn more about PdfGrid, 
 
Insert image to PDF table cell: https://www.syncfusion.com/kb/9746/how-to-add-two-images-in-one-pdf-table-cell-using-c-and-vb-net 
Working with shapes in PDF: https://help.syncfusion.com/file-formats/pdf/working-with-shapes 
Working with tables: https://help.syncfusion.com/file-formats/pdf/working-with-tables 
 
Please try the above sample in your end and let us know the result.

**Comment by bobotan** [comment]
I've tried it. It works！ strong strong strong！
