### ISSUE TITLE
Does pdffont support Chinese

### ISSUE THREAD

**Issue by bobotan** [syncfusion/wpf-demos#6]
Does pdffont support Chinese？

**Comment by Gowthamgautam** [comment]
Hi Boboton,

Thank you for contacting Syncfusion support.

Yes. We have support for drawing the text with Chinese characters in a PDF document using our Syncfusion PDF library. We have created a simple sample to draw the Chinese characters in a PDF document using PdfTrueTypeFont class, it generates the PDF document properly. The provided true type font should support the characters to draw in a PDF document. We have attached the sample for your reference. Please find the sample from below link,

[Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/CreatePDFSampleFont68440647 )

Please find the code snippet to draw the text with Chinese characters in a PDF document,

`PdfDocument document = new PdfDocument();
//Add a page to the document
PdfPage page = document.Pages.Add();
//Create PDF graphics for the page
PdfGraphics graphics = page.Graphics;
//Set the pdf true type font
PdfFont font = new PdfTrueTypeFont("../../Font/arial-unicode-ms.ttf", 16);
//Draw the text
graphics.DrawString("你好，世界", font, PdfBrushes.Black, new PointF(0, 0));
//Save the document
document.Save("Output.pdf");
`

Please refer to this below link for more information,
**UG**: https://help.syncfusion.com/file-formats/pdf/working-with-text#drawing-text-using-different-fonts 
**KB**: https://www.syncfusion.com/kb/896/how-to-draw-chinese-japanese-and-korean-language-text-in-pdf-using-c-and-vb-net  

**Note**: I work for Syncfusion.

Regards,

Gowthamraj Kumar

**Comment by bobotan** [comment]
i just want say six six six!
